name: "Update Manifest and Commit Changes"
description: "Checks out the repository, sets up Node, installs dependencies, updates manifest.json, formats, and commits/pushes changes signing the commit."
inputs:
  manifest-path:
    description: "The path to the manifest.json file."
    required: false
    default: "${{ github.workspace }}/manifest.json"
  schema-path:
    description: "The path to the plugin settings schema."
    required: false
    default: "${{ github.workspace }}/src/types/plugin-input.js"
  plugin-entry:
    description: "The path to the plugin entry file."
    required: false
    default: "${{ github.workspace }}/src/index.ts"
  commit-message:
    description: "The commit message."
    required: false
    default: "chore: updated manifest.json and dist build"
  node-version:
    description: "The version of Node.js to use."
    default: "20.10.0"
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      shell: bash
      run: |
        yarn install --immutable --immutable-cache --check-cache

    - name: Compile TypeScript files
      shell: bash
      run: |
        yarn tsc --project tsconfig.json -m commonjs

    - name: Build project
      shell: bash
      run: |
        yarn add -DE @vercel/ncc
        yarn ncc build ${{ inputs.plugin-entry }} -m

    - name: Update manifest configuration JSON
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');

          const { pluginSettingsSchema } = require('${{ inputs.schema-path }}');

          const manifestPath = '${{ inputs.manifest-path }}'
          const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));

          const configuration = JSON.stringify(pluginSettingsSchema);

          manifest["configuration"] = JSON.parse(configuration);

          const updatedManifest = JSON.stringify(manifest, null, 2)
          console.log('Updated manifest:', updatedManifest);
          fs.writeFileSync(manifestPath, updatedManifest);

    - name: Format manifest using Prettier
      shell: bash
      run: |
        yarn add -DE prettier
        yarn prettier --write .

    - name: Get GitHub App token
      if: inputs.app-id != '' && inputs.app-private-key != ''
      uses: tibdex/github-app-token@v1.7.0
      id: get_installation_token
      with:
        app_id: ${{ inputs.app-id }}
        private_key: ${{ inputs.app-private-key }}

    - name: Commit and Push changes
      shell: bash
      env:
        GITHUB_TOKEN: ${{ steps.get_installation_token.outputs.token || github.token }}
      run: |
        git config --global user.name "GitHub App"
        git config --global user.email "github-app@example.com"
    
        app_token="${{ steps.get_installation_token.outputs.token }}" # Assuming this outputs your app token
    
        user_info=$(curl -s -H "Authorization: token $app_token" https://api.github.com/user)
    
        user_name=$(echo "$user_info" | jq -r .name)
        user_email=$(echo "$user_info" | jq -r .email)
    
        if [ "$user_email" == "null" ]; then
          user_email="github-app@example.com"
        fi
        
        # Configure Git with the retrieved user information
        git config --global user.name "$user_name"
        git config --global user.email "$user_email"
        git remote set-url origin https://${{ env.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
    
        git add "${{ inputs.manifest-path }}"
        git add -f ${{ github.workspace }}/dist/\*
        if [ -n "$(git diff-index --cached --name-only HEAD)" ]; then
          git commit -m "${{ inputs.commit-message }}" || echo "Commit failed"
          # Attempt to pull and resolve conflicts
          git pull origin ${{ github.ref_name }} || {
            echo "Rebase failed, force pushing changes."
            git push --force origin HEAD:${{ github.ref_name }}
            exit 0
          }
          git push origin HEAD:${{ github.ref_name }}
        else
          echo "No changes to commit"
        fi